services:
  db-mx:
    image: postgres:12.5
    container_name: mx_news_bot-db-mx
    environment:
      POSTGRES_DB: mx
      POSTGRES_USER: mx
      POSTGRES_PASSWORD: mxpassword
    ports:
      - "6444:5432"
    volumes:
      - mx_news_bot_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    stop_grace_period: 3s
    networks:
      mx_news_bot_net:
        aliases:
          - db-mx

networks:
  mx_news_bot_net:
    external: true

volumes:
  mx_news_bot_db_data:
    name: mx_news_bot_db_data
